# Generated by Django 4.2.5 on 2023-10-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='autor',
            new_name='author',
        ),
    ]
